### ISSUE TITLE
[BUG] Error swapping the whole balance displayed on the Wallet app DEX

### ISSUE THREAD

**Issue by nenantonov** [Hydra-Chain/node#13]
**Description:**
When trying to swap the whole HYDRA balance displayed the Wallet app DEX, the transaction is not going through without error message.

**Test performed to demo the bug:**
The test is performed with Wallet app DEX (from production).

To monitor the available UTXOs a desktop staking wallet (the staking wallet with GUI) is installend on AWS. The purpose is just to be able to easily view the available UXTOs before and after each transaction on the DEX. The same address as the address used for the Wallet app DEX is imported in the staking wallet. There are no immature UTXOs. The staking wallet is not staking. The UTXO set before the swap is the following:

![image](https://user-images.githubusercontent.com/44605287/155783675-e680becd-ef19-4333-a520-84a7cf9c7993.png)

A swap HYDRA > GOMT with the displayed HYDRA balance is attempted. The swap is not going through and no error message is displayed. Instead the Confirm Swap window is reloaded.

https://user-images.githubusercontent.com/44605287/155785474-ee9075f6-2247-4aaf-bffb-c3f7c70e581e.mp4

**Expected behaviour:**
The whole balance displayed on the Wallet app DEX should be used for the swap, after the gas fee is deducted from the balance and the rest is swapped.

**Comment by RosenKrumov** [comment]
Not relevant for hydra node code
