### ISSUE TITLE
[BUG] Issue with hydra_v0.18.5.7 on Ubuntu 18.04

### ISSUE THREAD

**Issue by ejkreukniet** [Hydra-Chain/node#17]
The downloadable aarch64 does not run on Ubuntu 18.04 due to GLIBC_2.28 dependency. Also building from source does not work:
*** No rule to make target 'cpp-ethereum/utils/libscrypt/b64.c', needed by 'cpp-ethereum/utils/libscrypt/libbitcoinconsensus_la-b64.lo'.  Stop.

**Comment by RosenKrumov** [comment]
Closed as obsolete.
