### ISSUE TITLE
Error when installing node

### ISSUE THREAD

**Issue by TamedByMusic** [Hydra-Chain/node#5]
sudo apt-get install libdb4.8-dev libdb4.8++-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package libdb4.8++-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package libdb4.8-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libdb4.8-dev' has no installation candidate
E: Package 'libdb4.8++-dev' has no installation candidate

**Comment by RosenKrumov** [comment]
Fixed, instructions in hydra docs site
