### ISSUE TITLE
Call contract no function loaded from Abi

### ISSUE THREAD

**Issue by youtpout** [Hydra-Chain/node#8]
Hello,
I use the desktop wallet in windows with testnet, HYDRA version v0.18.5.5-43260a557-dirty (64-bit)

I have deployed a smartcontract, I add contract address and abi json in contract info window.
When I load the contract in Send to contract, I have all function loaded, but it doesn't load anything in call contract.

![send-contract](https://user-images.githubusercontent.com/10778684/136181472-fdf32412-3255-48d2-b147-4bf148bd486f.png)

![call-contract](https://user-images.githubusercontent.com/10778684/136181489-1c8ee847-141e-4956-8db1-e47082c5a314.png)

**Comment by RosenKrumov** [comment]
Closing this as obsolete.
